# Workflow Name
name: Convert Clash Rules to Sing-box Format

# Workflow Triggers
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Python and Cache Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: 3. Install Python Dependencies
        run: pip install pyyaml

      - name: 4. Clone External Rule Repository
        run: git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script.git temp_repo

      - name: 5. Convert YAML to Sing-box JSON
        shell: bash
        run: |
          mkdir -p rules
          
          find temp_repo/rule/Clash -type f \( -name '*.yaml' -o -name '*.yml' \) | grep -v 'No_Resolve' | while read -r yaml_file; do
            base_name=$(basename "${yaml_file%.*}.json")
            
            # Use a heredoc to pass Python code to avoid YAML parsing issues
            python3 - "$yaml_file" "rules/$base_name" <<EOF
import yaml
import json
import sys
import os

yaml_file = sys.argv[1]
json_file = sys.argv[2]

try:
    with open(yaml_file, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f) or {}
except Exception as e:
    print(f'Could not process {yaml_file}: {e}', file=sys.stderr)
    sys.exit(0)

mapping = {
    'DOMAIN': 'domain', 'DOMAIN-SUFFIX': 'domain_suffix', 'DOMAIN-KEYWORD': 'domain_keyword',
    'DOMAIN-REGEX': 'domain_regex', 'IP-CIDR': 'ip_cidr', 'IP-CIDR6': 'ip_cidr',
    'IP6-CIDR': 'ip_cidr', 'SRC-IP-CIDR': 'source_ip_cidr', 'PROCESS-NAME': 'package_name',
    'PROCESS-PATH': 'process_path', 'PROCESS-PATH-REGEX': 'process_path_regex',
    'PORT': 'port', 'PORT-RANGE': 'port_range', 'SRC-PORT': 'source_port',
    'SRC-PORT-RANGE': 'source_port_range'
}

rule = {}

for item in data.get('payload', []):
    if not item or not isinstance(item, str):
        continue
    parts = item.split(',', 1)
    if len(parts) != 2:
        continue
    t, v = parts[0].strip().upper(), parts[1].strip()
    if t in mapping:
        key = mapping[t]
        if key == 'domain_suffix' and not v.startswith('.'):
            v = '.' + v
        rule.setdefault(key, []).append(v)

clean_rule = {k: v for k, v in rule.items() if v}

if not clean_rule:
    sys.exit(0)

os.makedirs(os.path.dirname(json_file), exist_ok=True)

with open(json_file, 'w', encoding='utf-8') as f:
    json.dump({'version': 3, 'rules': [clean_rule]}, f, indent=2, ensure_ascii=False)

print(f'Successfully converted {yaml_file} to {json_file}')
EOF
          done

      - name: 6. Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/
          if ! git diff --cached --quiet; then
            git commit -m "feat(rules): Automatic update of sing-box rule files" -m "Source: blackmatrix7/ios_rule_script"
            git push
          else
            echo "No changes to commit."
          fi