name: Clone and Convert Clash YAML to JSON (exclude No_Resolve)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # UTC 每天凌晨0点触发

jobs:
  clone_and_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up Python and install PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyyaml

      - name: Clone ios_rule_script repo manually
        run: |
          git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script.git temp_repo

      - name: Convert YAML to JSON excluding No_Resolve files
        run: |
          mkdir -p rules
          find temp_repo/rule/Clash -type f \( -name '*.yaml' -o -name '*.yml' \) | grep -v 'No_Resolve' | while read -r yaml_file; do
            base_name=$(basename "${yaml_file%.*}.json")
            python3 -c "
import yaml, json, sys
f=open('$yaml_file', 'r', encoding='utf-8')
data = yaml.safe_load(f)
f.close()
with open('rules/' + '$base_name', 'w', encoding='utf-8') as out:
    json.dump(data, out, ensure_ascii=False, indent=2)
"
          done

      - name: Commit and push JSON files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/*.json
          if ! git diff --cached --quiet; then
            git commit -m "Convert Clash YAML to JSON excluding No_Resolve"
            git push
          else
            echo "No changes to commit"
          fi