name: Clone and Convert Clash YAML to JSON (exclude No_Resolve)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # UTC每天凌晨0点触发

jobs:
  clone_and_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 安装 Python 和 PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyyaml

      - name: 克隆 ios_rule_script 仓库
        run: |
          git clone --depth=1 https://github.com/blackmatrix7/ios_rule_script.git temp_repo

      - name: 转换 YAML 到 JSON（排除 No_Resolve）
        run: |
          mkdir -p rules
          find temp_repo/rule/Clash -type f \( -name '*.yaml' -o -name '*.yml' \) | grep -v 'No_Resolve' | while read -r yaml_file; do
            base_name=$(basename "${yaml_file%.*}.json")
python3 <<EOF
import yaml
import json

with open("$yaml_file", "r", encoding="utf-8") as f:
    data = yaml.safe_load(f)

with open("rules/$base_name", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
EOF
          done

      - name: 提交并推送改动
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/*.json
          if ! git diff --cached --quiet; then
            git commit -m "Convert Clash YAML to JSON excluding No_Resolve"
            git push
          else
            echo "No changes to commit"
          fi