name: Clone and Convert Clash YAML to JSON (exclude No_Resolve)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # UTC 时间每天凌晨0点执行，即北京时间早上8点

jobs:
  clone_and_convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 1

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyyaml

      - name: Convert YAML to JSON excluding No_Resolve files
        shell: bash
        run: |
          mkdir -p rules
          echo "Searching yaml files (excluding No_Resolve):"
          find rule/Clash -type f \( -name '*.yaml' -o -name '*.yml' \) | grep -v 'No_Resolve' | tee /dev/stderr | while read -r yaml_file; do
            base_name=$(basename "${yaml_file%.*}.json")
            json_file="rules/$base_name"
            python3 -c "import yaml,json; f=open('$yaml_file','r',encoding='utf-8'); d=yaml.safe_load(f); f.close(); f=open('$json_file','w',encoding='utf-8'); json.dump(d,f,ensure_ascii=False,indent=2); f.close()"
          done

      - name: Commit and push JSON files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/*.json
          git diff --cached --quiet || (git commit -m "Convert Clash YAML to JSON excluding No_Resolve" && git push)