name: Convert Clash YAML to JSON (exclude No_Resolve)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  convert_yaml_to_json:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyyaml

      - name: Convert YAML to JSON excluding No_Resolve files
        shell: bash
        run: |
          mkdir -p rules
          echo "Searching yaml files (excluding No_Resolve):"
          find rule/Clash -type f \( -name '*.yaml' -o -name '*.yml' \) | grep -v 'No_Resolve' | tee /dev/stderr | while read -r yaml_file; do
            json_file="rules/$(basename "${yaml_file%.*}.json")"
            python3 - <<EOF
import yaml
import json

yaml_path = "${yaml_file}"
json_path = "${json_file}"

with open(yaml_path, "r", encoding="utf-8") as f:
    data = yaml.safe_load(f)

with open(json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
EOF
          done

      - name: Commit and push JSON files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rules/*.json
          git diff --cached --quiet || (git commit -m "Convert Clash YAML to JSON excluding No_Resolve" && git push)