# Just test
name: Convert Clash YAML to sing-box JSON

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyYAML
        run: pip install pyyaml

      - name: Download Clash YAML
        run: |
          curl -L "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml" -o rules.yaml

      - name: Convert to sing-box JSON
        run: |
          mkdir -p rules
          python <<'EOF'
          import yaml, json, sys, os

          mapping = {
              "DOMAIN": "domain",
              "DOMAIN-SUFFIX": "domain_suffix",
              "DOMAIN-KEYWORD": "domain_keyword",
              "DOMAIN-REGEX": "domain_regex",
              "IP-CIDR": "ip_cidr",
              "IP-CIDR6": "ip_cidr",
              "IP6-CIDR": "ip_cidr",
              "SRC-IP-CIDR": "source_ip_cidr",
              "PROCESS-NAME": "package_name",
              "PROCESS-PATH": "process_path",
              "PROCESS-PATH-REGEX": "process_path_regex",
              "PORT": "port",
              "PORT-RANGE": "port_range",
              "SRC-PORT": "source_port",
              "SRC-PORT-RANGE": "source_port_range"
          }

          with open("rules.yaml", "r", encoding="utf-8") as f:
              data = yaml.safe_load(f) or {}

          rule = {}
          for item in data.get("payload", []):
              if not item or not isinstance(item, str):
                  continue
              parts = item.split(",", 1)
              if len(parts) != 2:
                  continue
              type_, value = parts[0].strip().upper(), parts[1].strip()
              if type_ in mapping:
                  field = mapping[type_]
                  if field == "domain_suffix" and not value.startswith("."):
                      value = "." + value
                  rule.setdefault(field, []).append(value)

          clean_rule = {k: v for k, v in rule.items() if v}

          if not clean_rule:
              print("No rules generated — skipping file write.")
              sys.exit(0)

          out = {"version": 3, "rules": [clean_rule]}
          os.makedirs("rules", exist_ok=True)
          with open("rules/globalmedia.json", "w", encoding="utf-8") as f:
              json.dump(out, f, indent=2, ensure_ascii=False)
          print("Wrote rules/globalmedia.json")
          EOF

      - name: Commit and push (only if file exists)
        run: |
          if [ -f rules/globalmedia.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add rules/globalmedia.json
            git commit -m "Update sing-box globalmedia rules" || echo "No changes"
            git push
          else
            echo "No rules/globalmedia.json generated — skipping push."
          fi